env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      before_install:
        - git submodule update --init --recursive
        - carthage build --no-skip-current
      script:
        - set -o pipefail
        - xcodebuild test -scheme Abstract | xcpretty -c
        - xcodebuild build-for-testing -scheme Abstract-iOS -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation)" | xcpretty -c
        - xcodebuild test -scheme Abstract-iOS -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation)" | xcpretty -c
        - xcodebuild build-for-testing -scheme Abstract-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p)' | xcpretty -c
        - xcodebuild test -scheme Abstract-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p)' | xcpretty -c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - git submodule update --init --recursive
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget https://swift.org/builds/swift-4.1-release/ubuntu1404/swift-4.1-RELEASE/swift-4.1-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.1-RELEASE-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-4.1-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift test
